version: '3.8'
services:
  app:
    container_name: jobs-be
    restart: unless-stopped
    build:
      context: ./docker/phpfpm
    environment:
      WEBROOT: '/var/www'
    volumes:
      - .:/var/www
    depends_on:
      - mysql
  nginx:
      container_name: jobs-nginx
      restart: unless-stopped
      build:
        context: ./docker/nginx
      ports:
        - ${DOCKER_WEB_PORT}:80
      volumes:
        - '.:/var/www'
        - './docker/nginx/logs:/var/log/nginx/'
      depends_on:
        - app
  mysql:
      image: mysql:8
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'


